name = "moobi-studio"
compatibility_date = "2024-04-24"

# Specify the output directory for Pages - required property
pages_build_output_dir = "dist"

# Disable caching to prevent large files
[env.production]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

# R2 asset binding for images/videos
[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "pub-fa2dabd7eff54614b1563a0863fb7cbc" 