name = "moobi-studio"
compatibility_date = "2024-04-24"

# Specify the output directory for Pages - required property
pages_build_output_dir = "dist"

# Runtime environment variables & bindings
[env.production]
# R2 asset binding for images/videos (runtime access)
# Ensure this is also configured in the Pages dashboard: Functions -> R2 bucket bindings
[[env.production.r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "cdn-images"

