name = "moobi-studio"
compatibility_date = "2024-04-24"

# Specify the output directory for Pages - required property
pages_build_output_dir = "dist"

# Disable caching to prevent large files
[env.production]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

# R2 asset binding for images/videos - Should be under env.production
[[env.production.r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "cdn-images" 